import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import "./../styles/main.css";
import AuthProvider from "@/lib/AuthProvider";
import SidebarWrapper from "@/components/layout/SidebarWrapper";
import NavbarWrapper from "@/components/layout/NavbarWrapper";
const inter = Inter({subsets: ["latin"], display: "swap"});
import {Toaster} from "react-hot-toast";
import {CustomThemeProvider} from "@/providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body className="bg-white selection:bg-[#d8ff2e] selection:text-black dark:bg-[#0a0a0a]">
        <CustomThemeProvider>
          <AuthProvider>
            <Toaster position="bottom-right" />
            <div className="bodywrapper bg-white relative flex dark:bg-[#0a0a0a]">
              <SidebarWrapper />
              <div className="flex-1 flex flex-col">
                <NavbarWrapper />
                <main>{children}</main>
              </div>
            </div>
          </AuthProvider>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
