type Post {
  id: ID!
  title: String!
  description: String!
  slug: String!
  date: DateTime!
  downloadLink: String!
  tags: [String!]!
  appVersion: String
  platforms: [String!]!
  publisher: String
  releasedDate: DateTime
  interfaceLanguages: [String!]!
  voiceLanguages: [String!]!
  systemRequirements: JSON!
  faqList: JSON!
  images: [String!]!
  author: User!
  authorId: String!
  status: PostStatus!
  createdAt: DateTime!
  updatedAt: DateTime!
}

enum PostStatus {
  DRAFT
  PUBLISHED
}

scalar DateTime
scalar JSON

input CreatePostInput {
  title: String!
  description: String!
  slug: String!
  date: DateTime!
  downloadLink: String!
  tags: [String!]!
  appVersion: String
  platforms: [String!]!
  publisher: String
  releasedDate: DateTime
  interfaceLanguages: [String!]!
  voiceLanguages: [String!]!
  systemRequirements: JSON!
  faqList: JSON!
  images: [String!]!
  status: PostStatus!
}

type Mutation {
  createPost(input: CreatePostInput!): Post!
}
